AWSTemplateFormatVersion: '2010-09-09'

Description: IAM Role for VKV Payments MNV

Parameters:

  Environment:
    Type: String
    AllowedValues:
      - dev
      - sat
      - prd

  ApplicationName:
    Type: String
    Default: vkv-payments-mnv

  RoleName:
    Type: String

  ManagedPolicyArns:
    Type: CommaDelimitedList
    Default: ""

  Owner:
    Type: String

  CostCenter:
    Type: String

Resources:

  ApplicationRole:
    Type: AWS::IAM::Role

    Properties:
      RoleName: !Ref RoleName

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns: !Ref ManagedPolicyArns

      Tags:
        - Key: Application
          Value: !Ref ApplicationName

        - Key: Environment
          Value: !Ref Environment

        - Key: Owner
          Value: !Ref Owner

        - Key: CostCenter
          Value: !Ref CostCenter

Outputs:

  RoleArn:
    Description: IAM Role ARN
    Value: !GetAtt ApplicationRole.Arn

  RoleName:
    Description: IAM Role Name
    Value: !Ref ApplicationRole